Add API reference for cases and query params
utrad-ical/circus-docs pull request #11
Opened 2023-02-20 09:31 UTC by makiyama-tky

2023-03-08 01:07 UTC, smikitky requested changes
-

2023-03-08 01:07 UTC, smikitky commented on docs/dev/search-query-parameters.md
> +: Skips a specified number of search results.
`skip` なんていうクエリパラメーターはありません。コードを読み直してください。https://github.com/utrad-ical/circus/blob/52e302f6afbf25c947bc9fbbb53dd5f1600ca1cc/packages/circus-api/src/api/performSearch.ts#L43-L93

2023-03-08 01:07 UTC, smikitky commented on docs/dev/search-query-parameters.md
> +}
これ、ひとつの `$and` にまとめても良いですよね。例として不適切なのでましな例にしてください。

2023-03-08 01:07 UTC, smikitky commented on docs/dev/search-query-parameters.md
> +## Available Filter Keys
こういうエンドポイントに個別の情報は case とか series とかの個々のページに移してください。ここには「例えば series では domain をキーとして利用できます」みたいな簡単な説明があれば十分です。

2023-03-23 10:55 UTC, makiyama-tky commented on docs/dev/api-examples/cases.md
> +: Skip a specified number of search results.
フィルタリングはできました。

2023-03-30 00:53 UTC, smikitky approved these changes

2023-03-30 00:53 UTC, merged